version: "3"
services:
  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    networks:
      - arbronnet

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    ports:
      - "1543:9000"
    command: server /data
    networks:
      - arbronnet

  queryer:
    build: ./queryer
    environment:
      RUST_LOG: info
      KEYS_FILE: /keys.txt
      LISTEN: 0.0.0.0:1539
      TIMEOUT: 15
    volumes:
      - ./keys.txt:/keys.txt
    networks:
      - arbronnet

  cache:
    build: ./cache
    depends_on:
      - redis
    environment:
      RUST_LOG: info
      REDIS_ADDRESS: redis://redis
      GET_ADDRESS: 0.0.0.0:1538
      SET_ADDRESS: 0.0.0.0:1537
      TTL: 0
    networks:
      - arbronnet

  router:
    build: ./router
    depends_on:
      - queryer
      - cache
    environment:
      RUST_LOG: info
      LISTEN_ADDRESS: 0.0.0.0:1540
      QUERYER_ADDRESS: queryer:1539
      CACHE_GET_ADDRESS: cache:1538
      CACHE_SET_ADDRESS: cache:1537
    ports:
      - "1540:1540"
    networks:
      - arbronnet

  reports:
    build: ./reports
    depends_on:
      - minio
    environment:
      LISTEN: :1542
      BUCKET_NAME: reports
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    ports:
      - "1542:1542"
    networks:
      - arbronnet

  frontend:
    build: 
      context: ./frontend
      args:
        - VUE_APP_API_URL=http://192.168.1.101:1540
        - VUE_APP_REPORTS_URL=http://192.168.1.101:1542
    ports:
      - "1541:80"
    networks:
      - "arbronnet"

networks:
  arbronnet:

volumes:
  redis:
    driver: local
